version: '3.8'

services:
  # MySQL Database Service
  mysqldb:
    image: mysql:8.0
    container_name: movies
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: movies
    ports:
      - "5000:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot Application Service
  movie-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-service
    ports:
      - "4000:4000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/movies
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123
    depends_on:
      - mysqldb
volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
