version: '3'
services:
  # Database Service
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=movies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - './postgres/init:/docker-entrypoint-initdb.d:ro'

  # Your Application Service
  app:
    build: .
    ports:
      - 4000:4000
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/movies
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
